---
title: "351 Final Project - Annabel Mendum"
output:
  html_document:
    df_print: paged
---



### Packages
```{r, message=FALSE}
library(statnet)
library(readr)
library(netseg)
library(texreg)
#library(intergraph)
#library(igraph)
```


### Importing the data
```{r, message=FALSE}
#networks
data1 <- read_table("s50_data/s50-network1.dat", col_names = as.character(1:50))
data2 <- read_table("s50_data/s50-network2.dat", col_names = as.character(1:50))
data3 <- read_table("s50_data/s50-network3.dat", col_names = as.character(1:50))

#node attributes
smoke <- read_table("s50_data/s50-smoke.dat", col_names = FALSE)
drugs <- read_table("s50_data/s50-drugs.dat", col_names = FALSE)
drink <- read_table("s50_data/s50-alcohol.dat", col_names = FALSE)
sport <- read_table("s50_data/s50-sport.dat", col_names = FALSE)
famchange <- read_table("s50_data/s50-familyevent.dat", col_names = FALSE)
```


### Making variables for node attributes 
```{r, message=FALSE}
smoke1 <- smoke$X1
drugs1 <- drugs$X1
drink1 <- drink$X1
sport1 <- sport$X1

smoke2 <- smoke$X2
drugs2 <- drugs$X2
drink2 <- drink$X2
sport2 <- sport$X2
famchange2 <- famchange$X1

smoke3 <- smoke$X3
drugs3 <- drugs$X3
drink3 <- drink$X3
sport3 <- sport$X3
famchange3 <- famchange$X2
```


### Attaching node attributes
```{r}
#time 1
edges1 <- as.edgelist.sna(data1)

net1 <- network(edges1, matrix.type="edgelist") 

net1 %v% "smoke" <- smoke1
net1 %v% "drugs" <- drugs1
net1 %v% "drink" <- drink1
net1 %v% "sport" <- sport1

summary(net1)


#time 2
edges2 <- as.edgelist.sna(data2)

net2 <- network(edges2, matrix.type="edgelist") 

net2 %v% "smoke" <- smoke2
net2 %v% "drugs" <- drugs2
net2 %v% "drink" <- drink2
net2 %v% "sport" <- sport2
net2 %v% "famchange" <- famchange2

summary(net2)


#time 3
edges3 <- as.edgelist.sna(data3)

net3 <- network(edges3, matrix.type="edgelist") 

net3 %v% "smoke" <- smoke3
net3 %v% "drugs" <- drugs3
net3 %v% "drink" <- drink3
net3 %v% "sport" <- sport3
net3 %v% "famchange" <- famchange3

summary(net3)
```


### Visualizations
```{r}
op <- par(mar = c(0,0,4,0),mfrow=c(1,3))
gplot(net1, main = "1995")
gplot(net2, main = "1996")
gplot(net3, main = "1997")

#smoking
op <- par(mar = c(0,0,4,0),mfrow=c(1,3))
gplot(net1, vertex.col = net1 %v% "smoke" + 1, main = "1995")
gplot(net2, vertex.col = net2 %v% "smoke" + 1, main = "1996")
gplot(net3, vertex.col = net3 %v% "smoke" + 1, main = "1997")
legend("bottomright", c("non", "occasional", "regular"), fill = c(2,3,4))

#cannabis use
op <- par(mar = c(0,0,4,0),mfrow=c(1,3))
gplot(net1, vertex.col = net1 %v% "drugs" + 1, main = "1995")
gplot(net2, vertex.col = net2 %v% "drugs" + 1, main = "1996")
gplot(net3, vertex.col = net3 %v% "drugs" + 1, main = "1997")
legend("bottomright", c("non", "tried once", "occasional", "regular"), fill = c(2,3,4,5))

#alcohol use
op <- par(mar = c(0,0,4,0),mfrow=c(1,3))
gplot(net1, vertex.col = net1 %v% "drink" + 1, main = "1995")
gplot(net2, vertex.col = net2 %v% "drink" + 1, main = "1996")
gplot(net3, vertex.col = net3 %v% "drink" + 1, main = "1997")
legend("bottomright", c("non", "once or twice a year", "once a month", "once a week", 
                        "more than once a week"), fill = c(2,3,4,5,6))

#sports
op <- par(mar = c(0,0,4,0),mfrow=c(1,3))
gplot(net1, vertex.col = net1 %v% "sport" + 1, main = "1995")
gplot(net2, vertex.col = net2 %v% "sport" + 1, main = "1996")
gplot(net3, vertex.col = net3 %v% "sport" + 1, main = "1997")
legend("bottomright", c("not regular", "regular"), fill = c(2,3))

#family change
op <- par(mar = c(0,0,4,0),mfrow=c(1,3))
gplot(net1, main = "1995")
gplot(net2, vertex.col = net2 %v% "famchange" + 1, main = "1996")
gplot(net3, vertex.col = net3 %v% "famchange" + 1, main = "1997")
legend("bottomright", c("no change", "change"), fill = c(2,3))
```



## Analyses

### Transitivity and Density
```{r}
c(gtrans(net1), gtrans(net2), gtrans(net3))

c(gden(net1), gden(net2), gden(net3))
```

### Reciprocated ties
```{r}
# proportion symmetric dyads
c(grecip(net1, measure="dyadic.nonnull"), 
  grecip(net2, measure="dyadic.nonnull"), 
  grecip(net3, measure="dyadic.nonnull"))

# proportion reciprocated ties
c(grecip(net1, measure="edgewise"), 
  grecip(net2, measure="edgewise"), 
  grecip(net3, measure="edgewise"))

```



### Homophily/Segregation Statistics
```{r, message=F}
# changing into igraph objects
library(intergraph)
inet1 <- asIgraph(net1)
inet2 <- asIgraph(net2)
inet3 <- asIgraph(net3)

detach(package:statnet)
library(igraph)
```

```{r}
#EI index
c(ei(inet1, "smoke"), ei(inet2, "smoke"), ei(inet3, "smoke"))
c(ei(inet1, "drugs"), ei(inet2, "drugs"), ei(inet3, "drugs"))
c(ei(inet1, "drink"), ei(inet2, "drink"), ei(inet3, "drink"))
c(ei(inet1, "sport"), ei(inet2, "sport"), ei(inet3, "sport"))

#Coleman's homophily
coleman(inet1, "smoke")
coleman(inet2, "smoke")
coleman(inet3, "smoke")

coleman(inet1, "drugs")
coleman(inet2, "drugs")
coleman(inet3, "drugs")

coleman(inet1, "drink")
coleman(inet2, "drink")
coleman(inet3, "drink")

coleman(inet1, "sport")
coleman(inet2, "sport")
coleman(inet3, "sport")

```


## ERGM

### Only edges (null model)
```{r, message=F}
# time 1
edgesergm1 <- ergm(net1 ~ edges, control=control.ergm(
  MCMC.samplesize=5000,
  MCMC.burnin=10000,
  MCMLE.maxit=10,
  seed=40))

# time 2
edgesergm2 <- ergm(net2 ~ edges, control=control.ergm(
  MCMC.samplesize=5000,
  MCMC.burnin=10000,
  MCMLE.maxit=10,
  seed=40))

# time 3
edgesergm3 <- ergm(net3 ~ edges, control=control.ergm(
  MCMC.samplesize=5000,
  MCMC.burnin=10000,
  MCMLE.maxit=10,
  seed=40))

```

```{r}
#time 1
screenreg(edgesergm1)

#time 2
screenreg(edgesergm2)

#time 3
screenreg(edgesergm3)
```


### Reciprocity
```{r, message = F}
# time 1
recipergm1 <- ergm(net1 ~ edges+mutual, control=control.ergm(
  MCMC.samplesize=5000,
  MCMC.burnin=10000,
  MCMLE.maxit=10,
  seed=40))

# time 2
recipergm2 <- ergm(net2 ~ edges+mutual, control=control.ergm(
  MCMC.samplesize=5000,
  MCMC.burnin=10000,
  MCMLE.maxit=10,
  seed=40))

# time 3
recipergm3 <- ergm(net3 ~ edges+mutual, control=control.ergm(
  MCMC.samplesize=5000,
  MCMC.burnin=10000,
  MCMLE.maxit=10,
  seed=40))
```

```{r}
# time 1
or1=exp(coef(recipergm1)) #odds ratio
or1
plogis(coef(recipergm1))
screenreg(list(edgesergm1,recipergm1))

# time 2
or2=exp(coef(recipergm2))
or2
plogis(coef(recipergm2))
screenreg(list(edgesergm2,recipergm2))

# time 3
or3=exp(coef(recipergm3))
or3
plogis(coef(recipergm3))
screenreg(list(edgesergm3,recipergm3))
```


### Including node attributes 
```{r, message=F}
# time 1
nodeattrergm1 <- ergm(net1 ~ edges + mutual + nodefactor("smoke") + nodefactor("drugs") +
                        nodefactor("drink") + nodefactor("sport"), control=control.ergm(
                          MCMC.samplesize=5000, 
                          MCMC.burnin=10000, 
                          MCMLE.maxit=10, 
                          seed=40))

# time 2
nodeattrergm2 <- ergm(net2 ~ edges + mutual + nodefactor("smoke") + nodefactor("drugs") +
                        nodefactor("drink") + nodefactor("sport"), control=control.ergm(
                          MCMC.samplesize=5000, 
                          MCMC.burnin=10000, 
                          MCMLE.maxit=10, 
                          seed=40))

# time 3
nodeattrergm3 <- ergm(net3 ~ edges + mutual + nodefactor("smoke") + nodefactor("drugs") +
                        nodefactor("drink") + nodefactor("sport"), control=control.ergm(
                          MCMC.samplesize=5000, 
                          MCMC.burnin=10000, 
                          MCMLE.maxit=10, 
                          seed=40))

# time 3 again with only the good ones
nodeattrergm3good <- ergm(net3 ~ edges + mutual + nodefactor("smoke") + nodefactor("drugs"), 
                      control=control.ergm(
                          MCMC.samplesize=5000, 
                          MCMC.burnin=10000, 
                          MCMLE.maxit=10, 
                          seed=40))

```

```{r}
# time 1
summary(nodeattrergm1)
plogis(coef(nodeattrergm1))
screenreg(list(edgesergm1, recipergm1, nodeattrergm1))

# time 2
summary(nodeattrergm2)
plogis(coef(nodeattrergm2))
screenreg(list(edgesergm2, recipergm2, nodeattrergm2))

# time 3
summary(nodeattrergm3)
plogis(coef(nodeattrergm3))
screenreg(list(edgesergm3, recipergm3, nodeattrergm3))

# time 3 better
summary(nodeattrergm3good)
plogis(coef(nodeattrergm3good))
screenreg(list(edgesergm3, recipergm3, nodeattrergm3good))
```



### Including homophily parameter (dyadic covariates)
```{r, message=F}
# time 1
homoergm1 <- ergm(net1 ~ edges + mutual + nodematch("smoke") + nodematch("drugs") +
                        nodematch("drink") + nodematch("sport"), control=control.ergm(
                          MCMC.samplesize=5000, 
                          MCMC.burnin=10000, 
                          MCMLE.maxit=10, 
                          seed=40))

# time 2
homoergm2 <- ergm(net2 ~ edges + mutual + nodematch("smoke") + nodematch("drugs") +
                        nodematch("drink") + nodematch("sport"), control=control.ergm(
                          MCMC.samplesize=5000, 
                          MCMC.burnin=10000, 
                          MCMLE.maxit=10, 
                          seed=40))

# time 3
homoergm3 <- ergm(net3 ~ edges + mutual + nodefactor("smoke") + nodefactor("drugs") +
                    nodematch("smoke") + nodematch("drugs") + nodematch("drink") + 
                    nodematch("sport"), control=control.ergm(
                          MCMC.samplesize=5000, 
                          MCMC.burnin=10000, 
                          MCMLE.maxit=10, 
                          seed=40))

```

```{r}
# time 1 
summary(homoergm1)
plogis(coef(homoergm1))
screenreg(list(edgesergm1, recipergm1, homoergm1))

# time 2
summary(homoergm2)
plogis(coef(homoergm2))
screenreg(list(edgesergm2, recipergm2, homoergm2))

# time 3
summary(homoergm3)
plogis(coef(homoergm3))
screenreg(list(edgesergm3, recipergm3, nodeattrergm3good, homoergm3))
```


